lib/jit_preloader/active_record/base.rb
spec/lib/jit_preloader/preloader_spec.rb
spec/support/models.rb

Add the ability to preload an aggregate method on associations. 
This will let you do a just in time preload of an association count, or a maximum, or a sum, etc.

Allow the abilility to preload aggregate methods on an association

---

Gemfile.lock
README.md
lib/jit_preloader/active_record/base.rb
lib/jit_preloader/version.rb

Allow nil to be a default. 
If the association has a provided scope, we need to execute that so we don't silently drop extra conditions

Bug Fixes from 0.0.5

---

lib/jit_preloader/active_record/base.rb
spec/lib/jit_preloader/preloader_spec.rb
spec/support/database.rb
spec/support/models.rb

This adds support for has_many_aggregate against polymorphic associations.  Previously the query lacked a where condition on the polymorphic type and so would give bad counts with polymorphic associations with multiple types on the other end of the association.

Add support for polymorphic associations for has_many_aggregate

---

lib/jit_preloader/active_record/base.rb
spec/lib/jit_preloader/preloader_spec.rb
spec/support/models.rb

This adds support for has_many_aggregate on through relationships. Currently, the SQL generated is invalid because the query is missing a join and some conditionals. The specs that were added fail on the master branch but pass with the new functionality.

Feature has_many_aggregate on a through relationship.

---

lib/jit_preloader/active_record/base.rb
lib/jit_preloader/version.rb

The current approach to inject the functionality is to `include` a module which can have the affect of clobbering patches from other gems. `prepend` is a better approach, however it can still have issues with alias chains https://bugs.ruby-lang.org/issues/11120
A concrete example:
We ran into issues with this gem along side https://github.com/attr-encrypted/attr_encrypted which uses alias method chains. The solution is to ensure that any gem that uses alias chains is loaded first then gems which prepend.
Implementation:
ActiveSupport::Concern is built to be used with `include` not `prepend` so we need to use the `prepended` hook to add class methods and there is no reason to use ActiveSupport concern anymore.

Use prepend instead of include to patch ActiveRecord::Base

---

lib/jit_preloader/active_record/base.rb
lib/jit_preloader/version.rb
spec/lib/jit_preloader/preloader_spec.rb
spec/support/database.rb
spec/support/models.rb

When using STI, `has_many_aggregate` to aggregate child models, under certain conditions, will fail to find the existing results. This is because the query uses an alias for the table join (since it's joining to the same table), but the `jit_preloader` logic naively uses the table's name.
These changes add logic to determine when a table alias is present in the query, and when one is, use that for the `jit_preloader` query.
While looking into this issue, we also discovered that the aggregate query fails to limit the results based on type when querying a child model through another child model. These changes also address that issue by including the type condition when querying through a child model.
```sql
SELECT COUNT(*) AS count_all, contacts.contact_book_id AS contacts_contact_book_id …
```

Add support for has_many_aggregate when working with STI models

---

Gemfile.lock
README.md
jit_preloader.gemspec
lib/jit_preloader/active_record/base.rb
lib/jit_preloader/preloader.rb
lib/jit_preloader/version.rb
spec/lib/jit_preloader/active_record/base_spec.rb

Fixes: https://github.com/clio/jit_preloader/issues/20
We add a `preload_scoped_relation` method onto instances of `ActiveRecord::Base` and we can use this to load a subset of an association. 
This method will leave the association untouched as to not create unusual side effects and will memoize the value based on a string passed into so the method can be called on the same object many times without worry.

Add method for dynamic loading

---

Gemfile.lock
lib/jit_preloader/active_record/base.rb
lib/jit_preloader/version.rb
spec/lib/jit_preloader/preloader_spec.rb
spec/support/models.rb

Continue https://github.com/clio/jit_preloader/pull/18
When the association scope is chained with conditions of other tables, the names of join tables are also added to `references_values`. It becomes impossible to identify the table alias name from the `references_values`.
The PR provides a way to customize the table alias name when the default way cannot figure out the correct value.
For a `ContactBook` has many `companies` and a `Company` has one `email_address`. When it counts the number of `companies` with blank `email_address`, the current implementation is wrong.
```
has_many :companies_with_blank_email_address, -> { joins(:email_address).where(email_addresses: { address: "" }) }, class_name: "Company"
has_many_aggregate :companies_with_blank_email_address, :count, :count, "*", …
```

Support overriding the table alias name

---

Gemfile.lock

Update `Gemfile.lock` to address https://github.com/clio/security-vulnerabilities/issues/158

Bump jit_preloader dependencies for rails CVEs

---

jit_preloader.gemspec
lib/jit_preloader.rb
lib/jit_preloader/active_record/associations/preloader/ar6_association.rb

This is another approach to #23 for adding ActiveRecord 6.0 support. It does not change any existing files like #24, but requires a separate file, if activercord version is >= 6.0.0.

Rails 6.0 support

---

jit_preloader.gemspec
lib/jit_preloader/active_record/associations/preloader/ar5_association.rb
lib/jit_preloader/active_record/associations/preloader/ar6_association.rb
lib/jit_preloader/active_record/base.rb
lib/jit_preloader/version.rb

Turns out that Rails 5.2 and 6.0 are not completely supported. 
Those versions of the gem have both a `ActiveRecord::Association::Preloader::Association` and a `ActiveRecord::Association::Preloader::ThroughAssociation`. Turns out the latter class redefines a method which makes it so the jit_preloader monkey patch doesn't run
https://github.com/rails/rails/tree/5-2-stable/activerecord/lib/active_record/associations/preloader
Further, in 6.0, when we are loading an association with a custom scope, Rails no longer assigns it to the association. Instead it leaves the data as accessible on the `ActiveRecord::Association::Preloader::Association` object. This means we need to update the `scoped_preload_association` method. 
Since the extended modules that monkey patch ActiveRecord call super, …

Ensure the specs pass for 5.2 and 6.0

---

lib/jit_preloader/version.rb

Before we can put out a release with https://github.com/clio/jit_preloader/pull/35 in it, we need to bump the version number. (Should have done that as part of https://github.com/clio/jit_preloader/pull/35, probably.)

Bump version to 1.0.1.

---

lib/jit_preloader/active_record/associations/collection_association.rb
lib/jit_preloader/active_record/associations/singular_association.rb
spec/lib/jit_preloader/preloader_spec.rb
spec/support/models.rb

Building off https://github.com/clio/jit_preloader/pull/35
We should also prevent loading instance dependent association automatically.

We should not try to preload instance dependent associations as they are not supposed through any kind of preloading

---

lib/jit_preloader/version.rb

We want to build a new version of the gem which contains https://github.com/clio/jit_preloader/pull/37, so here's a version bump.

Bump version to 1.0.2.

---

jit_preloader.gemspec
lib/jit_preloader/active_record/base.rb
lib/jit_preloader/version.rb
spec/lib/jit_preloader/active_record/base_spec.rb

https://github.com/clio/backend-infrastructure/issues/1687
Changes to ActiveRecord, between 5.17 and 6.0.3.5, has resulted in `ActiveRecord::Associations::Preloader#records_by_owner` returning `nil` instead of `[]` for empty associations.
The changes are shown here under `def records_by_owner` (line# ~29) https://github.com/rails/rails/compare/5aaaa1630ae9a71b3c3ecc4dc46074d678c08d67..c5929d5eb55b749bc124b3ccc2d79323d015701f#diff-97709b319ca07f6cd3f4d6b8a8c443d0cb3e7487696098be377aa9fa78907a35

`preload_scoped_relation` returns `nil` instead of `[]` for empty associations

---

Gemfile.5.2
Gemfile.5.2.lock
Gemfile.6.0
Gemfile.6.0.lock
Gemfile.6.1
Gemfile.6.1.lock
jit_preloader.gemspec
lib/jit_preloader/active_record/associations/preloader/ar5_association.rb
lib/jit_preloader/active_record/base.rb
spec/lib/jit_preloader/active_record/base_spec.rb
spec/lib/jit_preloader/preloader_spec.rb

Looks like when we some records and preload a singular association
e.g.
```ruby
companies = Company.where(id: [company1.id, company2.id]).jit_preload.all.to_a
expect(companies.map(&:contact_book)).to match_array [contact_book1, contact_book1]
```
and then change the foreign_key to that it is completely different than any record in the current set
```ruby
company = companies.each {|c| c.contact_book_id = contact_book2.id }
```
The association isn't properly cleared and you can end up with a situation where the association and the foreign_key do not align
eg.
```
comapny.contact_book_id != company.contact_book.id
```
This seems to be because there is an `||=` being used to set the `target` when we are associating the records to the owner. This appears fixed in Rails 6. The original method …

In some circumstances singular associations do not reload properly

---

Gemfile.6.1
Gemfile.6.1.4.1
Gemfile.6.1.lock
lib/jit_preloader/version.rb

Problem?
We want to attempt to get manage to run on rails 6.1.4.1; however, the jit_preloader only supports 6.1.0. 
This ticket resolves this by specifying creating a gemfile that supports 6.1.4.1

#43 allow support for rails 6.1.4.1

---

jit_preloader.gemspec
lib/jit_preloader/active_record/base.rb
lib/jit_preloader/preloader.rb

Fixes:
```
DEPRECATION WARNING: Calling `Preloader#initialize` without arguments is deprecated and will be removed in Rails 7.0. 
DEPRECATION WARNING: `preload` is deprecated and will be removed in Rails 7.0. Call `Preloader.new(kwargs).call` instead.
```

Rails 7 support

---

jit_preloader.gemspec
lib/jit_preloader/version.rb

This [pr](https://github.com/clio/jit_preloader/pull/50) introduces some breaking changes with how preloader handles arguments in rails 6 vs 7. To communicate this new jit_preloader as a breaking version change we'll bump a major version on the gem. We also want to update the gem spec to tell bundler that the new version requires activerecord 7.

bump version and active record dependency

---

lib/jit_preloader.rb
lib/jit_preloader/active_record/associations/preloader/ar7_association.rb

The monkey patch for `associate_records_to_owner` has changed between Rails 6 and Rails 7. 
In Rails 6.0 the [method](https://github.com/rails/rails/blob/6-0-stable/activerecord/lib/active_record/associations/preloader/association.rb#L73-L79) is missing a guard clause.
This is present in the [same method](https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/associations/preloader/association.rb#L229-L239) in Rails 7. 
This PR adds the rails 7 equivalent monkey patch in the same style that was used for the rails 5 & 6 patches.

Fix an issue with Rails7 monkey patch

---

lib/jit_preloader/version.rb

This will push a new version of the gem that includes Kyle d'Oliveira's [recent Rails 7 fixes.](https://github.com/clio/jit_preloader/pull/57#issuecomment-1795714899)

Update version to 2.0.1.

---

lib/jit_preloader/preloader.rb

We should only apply the jit_preloader preload when all records in the association haven't been preloaded. 
Otherwise we can get into some weird scenarios where the association fails to find any records
Using `loaded?` in the `load_target` method is only checks that the association we are looking at is not loaded, but other associations in the collection could be not loaded and that can cause errors. 
To illustrate this, you can do something like (from the specs)
```
companies = Company.where(id: [company1.id, company2.id]).preload(:contact_book).jit_preload.all.to_a
companies.each {|c| c.contact_book_id = contact_book2.id }
companies.map {|c| c.contact_book }
```
On line 1, the `contact_book` association is `preloaded` as expected.  
On line 2 the attribute for the contact book changes …

Error reloading an association after it is written

---

lib/jit_preloader.rb
lib/jit_preloader/active_record/associations/preloader/ar7_branch.rb

ActiveRecord Version >= 7.0.0 is introducing a [`active_record/associations/preloader/batch`](https://github.com/rails/rails/blob/v7.0.0.alpha1/activerecord/lib/active_record/associations/preloader.rb#L49C40-L49C82) file to process all associations in batch.
This introduces an [early check](https://github.com/rails/rails/blob/v7.0.0/activerecord/lib/active_record/associations/preloader/batch.rb#L17) of whether a association klass is a valid ActiveRecord::Base class.
Previously, we [override](https://github.com/clio/jit_preloader/blob/9f5abb11a40972968b4a9829d83cdea358c92fd0/lib/jit_preloader/active_record/associations/preloader/ar7_association.rb#L19) the `Preloader::Association` and `Preloader::ThroughAssociation` `run` method to direct return when a association.klass is not a valid …

Remove the association loader if the polymorphic class is not a child of ActiveRecord::Base

---

lib/jit_preloader.rb
lib/jit_preloader/active_record/base.rb
spec/lib/jit_preloader/preloader_spec.rb
spec/support/models.rb

From the [discourse post](https://discourse.clio.systems/t/side-affect-danger-for-changing-activerecord-model-association-utilization-of-jit-preloader/3406/2), we know that `has_many_aggregate` preload function may create inefficient query if the preload records are over the Mysql dive limit.
I am adding the ability to set a dive limit and slice the query base.
Not setting the dive limit will fall back to generate a single preload query.

Update has_many_aggregate preload function to slice query into multiple ones base on dive limit

---

jit_preloader.gemspec

to add the link from https://rubygems.org/gems/jit_preloader to https://github.com/clio/jit_preloader

Add homepage for gem

---

.gitignore
lib/jit_preloader/active_record/base.rb
lib/jit_preloader/version.rb
spec/lib/jit_preloader/active_record/base_spec.rb

During testing to upgrade Manage to latest jit_preloader(3.0.0, [build](https://buildkite.com/clio/manage/builds/263631)) I found that there's some places we use string as `base_association` name when calling `preload_scoped_relation` method([example](https://github.com/clio/themis/blob/7aeda8e18945472f8f966ff59de2c11cd07757e5/components/manage/app/serializers/manage/api/v4/text_message_conversation_serializer.rb#L94-L98)). 
With the latest version, this is causing the error of not able to find the association and properly(ActiveRecord native method of finding association is only allow passing a symbol of association name [reference](https://github.com/clio/jit_preloader/blob/95d99bfd87a435e5e89e065aa9b0a6e9149b5c27/lib/jit_preloader/active_record/base.rb#L64)) and therefore not caching …

Make sure we correctly find the association within preload_scoped_relation method
